// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	BookID     uuid.UUID `json:"book_id"`
	Code       string    `json:"code"`
	Title      string    `json:"title"`
	Publisher  string    `json:"publisher"`
	PublicDate time.Time `json:"public_date"`
	Version    int32     `json:"version"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
