// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	GetBook(ctx context.Context, bookID uuid.UUID) (Book, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
