// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"go-backend-template/api/controller"
	"go-backend-template/repository"
	"go-backend-template/usecase/book"
)

// Injectors from wire.go:

// Wire is a function that wires up the application.
func Wire(sqlDB *sql.DB) (*api.HandlerImpl, error) {
	store := repository.NewStore(sqlDB)
	useCase := book.NewBookUseCase(store)
	handlerImpl := api.NewHandlerImpl(useCase)
	return handlerImpl, nil
}

// wire.go:

var HandlerSet = wire.NewSet(api.NewHandlerImpl)

var UseCaseSet = wire.NewSet(book.NewBookUseCase)

var RepositorySet = wire.NewSet(repository.NewStore)
